### ISSUE TITLE
heavy js and ckeditor

### ISSUE THREAD

**Issue by peterdd** [flyspray/flyspray#100]
TODO Only load the ckeditor stuff when there is an textarea field in the loaded page.
TODO Only use the ckeditor extensions/plugins we really need for writing tasks or comments.

Do we really need a full blown ckeditor monster with all that plugins??? 

Using flyspray with that blown up javascript is so much slower
than when using flyspray with browser setting javascript.enabled= false.

For what reason the prototype and scriptaculous stuff is necessary? If its used, can it be replaced by something smaller JS or pure HTML(5) / CSS ?

**Comment by Psychokiller1888** [comment]
Duh..... We've planned a 1.0 release, so if we keep going on adding stuffs and stuffs it will be released in 2016. I'd say now it's source stabilising time, making sure everything works, not adding and modding.
The actual editor is not even enough, doesn't provide colors/size in my opinion. I think you're best of creating your own THEME without JS as JS seem to be your concern...

**Comment by peterdd** [comment]
This topic is no 'must be done' for 1.0.

Well, I just want a fast, secure flyspray. And reviewing the stuff that is loaded is part of it. And isn't the time before release the time to review what is necessary and what was experimental stuff like cleaning the kitchen after cooking? An old 0.9.7 integrated in joomla is faster and smaller.

Extra Theme is no option, there is a lot more stuff outside flyspray. 

![flyspray_loading](https://cloud.githubusercontent.com/assets/1839154/6347605/8a682d6a-bc19-11e4-9f5b-d51bc39e5dd5.png)

**Comment by Psychokiller1888** [comment]
As I always say, everything can be changed, cleaned up and made faster. But it must stay user friendly and take in consideration that a majority of users have high speed Internet access, aren't using FS on  their phones etc etc. So yes, cleanup is good, if you feel like doing it, great! But we freeze the sources on March 15th
