### ISSUE TITLE
Flyspray 1.0

### ISSUE THREAD

**Issue by Psychokiller1888** [flyspray/flyspray#101]
Hi all!

After discussing with Jordan, I think it's slowly time to speak about a 1.0 release... It is needed. 1.0 release is not the release that will revolution the world, but will be the revival release! 1.0 has been announced since 2012 and for reasons we all do understand never came out.

So the plan is for now (if needed):
- Stabilize the sources
- Fix security issues
- Get quick and real ideas about that composer
- Fix graphical output
- Work on the documentation (help welcome)
- Think of a real website, with a place for users to share together. (I have hosting plans available if you want). We are actually discussing in 3 places: Here, wikia, and Google groups... Not ok imo.

I think that, letting peterdd and Jouni finish their work is a good idea and plan a complete feature freeze for march the 15th 2015 is a good idea.

For real time discussion add me on skype, i'll invite you in the FS group. Make sure to specify your dev nickname, as the group is dev only.

**Comment by jahto** [comment]
I'm going to be ready within a few days so even the previously planned feature freeze on 1st March is ok for me. But I too think that peterdds' work is important, so I'd say: total feature freeze with bug fixes only and an alpha/beta release after he's finished. Hopefully already earlier than 15th March.

Didn't know there's a google group too...have to search for it.

**Comment by Psychokiller1888** [comment]
Well I proposed 15th of March, seeing what is committed lately it will need at least a week to review I think... And mid March is almost here... 

The Google group address is on the  .org website

**Comment by peterdd** [comment]
Psychokiller1888, what do you mean with  "and for reasons we all do understand never came out."

Please tell me more, I don't know. I know flyspray from times, when it was integrated in CMS Joomla 1.0.x around 10 years ago as Joomla extension but don't know about dev structure the whole time.

Am I right that except Jordan all the peoples listet at http://flyspray.org/team can be seen as former/retired team?

floele, the owner(?) of flyspray.org seems still active, but more on his products.
One of his collegues renewed the ssl cert after contacting over his forum https://forum.cdburnerxp.se/topic/9872-c-ot-bugsflysprayorg/

I didn't knew about the google mailing list until last week, lol. But this github is good, i like it.

**Comment by Psychokiller1888** [comment]
Well the reason being that everybody at flyspray does that for free, in their free time, so we can't expect anything from that. I mean, if they did not have enough time to actually stabilize and push out a 1.0 it's because they were busy at other things... That's why I contacted Jordan to see if I could help revive the whole, and it looks that we ar now three aboard for 1.0

**Comment by jordanmendler** [comment]
You got it! It's hard to support free software on a volunteer basis. It
tends to go in spurts as people get passion and free time. We had a strong
spurt to push out the last release and then neared but never completed 1.0.
I made several attempts to gain interest in what seemed like more
sustainable models to fund 1 or 2 dedicated offshore developers (e.g.
finding recurring donors, cloud-based subscription model, paid/preferred
support, pay for feature development, etc), but noone ever seemed
interested in shelling out money beyond the occasional $10-50 donation here
and there

_________________

Jordan Mendler
President & Chief Technology Officer
The Veloz Group | www.thevelozgroup.com

**Comment by jordanmendler** [comment]
With that said there are still many subscribers on the google group and
bugs.flyspray.org. I think in general we should try to push discussions and
bug tracking to those instead of doing so through github, as that is more
likely to then rally feedback, excitement, and patches from the base of
legacy users. But frankly, as long as people are contributing code to
better flyspray, I am super excited and don't really care how or where
things are being coordinated!

I also know a new home page was developed at some point but never pushed
lived. I think it is under a separate directory in github. If that is ready
for showtime, perhaps we can push on floele to point flyspray.org there
instead

_________________

Jordan Mendler
President & Chief Technology Officer
The Veloz Group | www.thevelozgroup.com

**Comment by peterdd** [comment]
It is flyspray.github.io
and website http://flyspray.github.io/

I made a pull request a few days ago for correction the screenshot links, but nobody reacted or merged it.
So do someone has contact to galactic-void or manage that site?

**Comment by Psychokiller1888** [comment]
Makes one more place... Honestly, when type g flyspray on Google, we get on wikia. In my opinion, for the sake of FS that should be urgently taken care of. One place, where to discuss, report, release, announce. That one place is wherever you want, but must include community tools. We should use  FS ourselves also

**Comment by jahto** [comment]
For my part, the feature freeze happened a few minutes ago. Now only bug fixes and maybe some really small changes based on feedback.

**Comment by peterdd** [comment]
what exactly do you mean with 'wikia'? 
The first hits of 'g flyspray' lead to dokuwiki.org pages when I search from a place in germany.

I found new out they used flyspray until 26 February 2014 as their bug tracking tool but switched to github. See https://www.dokuwiki.org/bugs
They even had a page for flyspray modification too: 
https://www.dokuwiki.org/plugin:authmysql:flyspray

**Comment by peterdd** [comment]
Well, flyspray.org is a good domain as first source for flyspray and use of flyspray as its own bugracker should be a good motivation.

But we do the coding work on github.com and its so comfortable here :-) Even github oauth
can be used. (So let's update bugs.flyspray.org so we gihub coders can login easy there for doing work on bugs.flyspray.org :-) )
I use my Google account extremely seldom, so I don't follow Google Mailings lists.

Also we should collect some info about in which other software projects flyspray is/was used.

- I know of Joomla had fully adapted version of flyspray as 3rd party component, later a bridge component.
- maybe egroupware had flyspray integrated, but maybe replaced it by other solutions.

**Comment by Psychokiller1888** [comment]
@jahto Great! Thanks for all this effort work
@peterdd Auto completion added a to "wiki" as I'm often refering to "wikia" for another project. I meant "wiki"

So, now I see one last big step, that's the one you proposed peterdd, being the installer... I think it's quiet simple, if idea to make it simplier, why not. But my main concern stay composer... Brainstorm ideas to make it more integrated! :)

**Comment by peterdd** [comment]
Here an other topic for releasing 1.0 and bring all that translation more to 100%:

 Integrate the existing translation tools in lang/  into Flyspray without the need to edit the php code to let also nontechnical users translate Flyspray to their language.

Should use an existing flyspray permission to restrict access when integrated..

Then these nontechnical users can contribute to the flyspray much more easily just by submitting the resulting lang/$lang.php to the project.

And they easy can adjust the translation to their own flavor/ company rules wordings.
 (like changing german Manntage to Personentage. Personentage sounds dull, but if if the company is addicted to "political correctness" they can adapt to that...)

**Comment by Psychokiller1888** [comment]
I totally agree, that langedit.php drives me nuts, the need to edit always... I wanted it in the admin pannel

**Comment by peterdd** [comment]
So, first step of integrating translations into admin panel done.

@jahto: I can't enter 8:00 as 8 hour per manday. The result that is shown after saving the form is 0:01...
For selecting display formats I want some 'Units officially accepted for use with the SI' preselected:
h for hours
min for minutes

So a value of (75*60) seconds in the database can be shown as:
75 min
or 
1 h 15 min

**Comment by jahto** [comment]
The problem seems to be something else. The value in database actually gets updated, and if you after saving switch once to tasklist and then back, you see the right value. Ill track down why it doesn't SEEM to be updated.

I'll add the last effort format too and change minutes format to use min instead of m sometime in the near future, I'm a bit busy just now.

**Comment by peterdd** [comment]
@Psychokiller1888: You can now pull and merge my branch to master if you want.
Not perfect translation integration in the admin page yet, but worked for me as a step forward.

**Comment by peterdd** [comment]
@jahto: I made that translation changes yet.
 If you have flyspray merge rights you can pull and merge my branch too. :-)

**Comment by Psychokiller1888** [comment]
There is no merge request... I have rights but send the merging request pls

**Comment by peterdd** [comment]
Ok, my laptop got broken last weekend and now I'm sitting in front of a very loud prehistoric, slow pc with firefox 14 not able to do a pull request on github.com. *rolleye* . I will do that if I'm at work later today.

**Comment by jahto** [comment]
That must have been a really fun birthday weekend in Berlin if it broke your laptop...

**Comment by peterdd** [comment]
Na, the display broke on saturday before driving to Berlin.

But Club Mate Wodka is still a very good party drink, although I would not call me a hipster. :-)

We got 5am back to our friends flat, nobody puked (well, it was a 30th birthday party, so we are experienced party people ;-) ) and slept until 2pm. One of the guys cutted a whole wood while sleeping but after 1 hour we all slept fine.

**Comment by Psychokiller1888** [comment]
Chainsaw'ing during party sleeps is totally understandable... Just saying that, because I'm pretty good at it as well :) And why puke? I mean, you paid everything you drunk, surely won't waste it...

**Comment by Psychokiller1888** [comment]
Lets push your last addons, as sunday 23:59:59:999 GMT+1 we feature freeze and release alpha on monday. Then we'll put the last efforts in debuging and completing the open points here and on FS

**Comment by jahto** [comment]
Ok. I've got still one feature coming in really late, implemented FS#1836. It's something that both I and Jordan have an actual use case for, so it got somewhat of "big priority boost" in the last days before feature freeze, and I could do the work and testing mostly on paid-for time just to get it in. Pull request coming within minutes.

**Comment by Psychokiller1888** [comment]
Easy dude, I'll still pull things even if over freeze time if needed :)

**Comment by Psychokiller1888** [comment]
I must say I quiet honestly don't understand the button in the quick action menu...... It's like if we had the "bold", "italic" etc button in the edit menu of Word... Imo they should be links, as they are in a menu. Cause now everything else is a link and we have three buttons, out of nowhere there

**Comment by jordanmendler** [comment]
Do you have time to hop on a call? Once 1.0 rolls out we can build a
cloud-based Flyspray. I have a lot of credits on EC2 so we can run it there


________________________Jordan Mendler
[image: The Veloz Group]
The Veloz Group
President & Chief Technology Officer
jordan@thevelozgroup.com
www.thevelozgroup.com

**Comment by Psychokiller1888** [comment]
Check your Skype Jordan

**Comment by peterdd** [comment]
This was just made for addressing token system as security fix. We can't just use links here as they are actions that change data in the db and must send token in a form request. 

If you can't wait you can adapt the css for that "now buttons" so that they look again like the dark links.

I'm still unhappy with the layout of the whole task view page layout and refused to fix that blue button appearance in the quickaction menu if the whole appearance and usability of the page must be reviewed/rethinked as a whole.

**Comment by Psychokiller1888** [comment]
That's also why I did not remove it, as it was clearly showing that the hidden inputs were needed

**Comment by Psychokiller1888** [comment]
We are live:

http://www.flyspray.org/docs/download/

**Comment by peterdd** [comment]
Do you made dokuwiki syntax the default for 1.0alpha? At least bugs.flyspray.org should stay on dokuwiki syntax until all issues dokuwiki vs. freetext/html solved.

**Comment by jahto** [comment]
Ok, so online notifications backend went in without a user interface and peterdd is too busy ti implement it. Is it ok for you guys if I cook up something by copying everything used for pending project manager requests and make necessary modifications to use almost same mechanism for online notifications ui? Could get it finished before weekend probably.

**Comment by Psychokiller1888** [comment]
FS 1.0 is delayed for as long as the theme is not ok

**Comment by Neustradamus** [comment]
I think that it can be released soon because stable version is needed to solve all CVEs...

**Comment by Neustradamus** [comment]
@jordanmendler is dead?

----------------------------------

Dear @peterdd,

A long time ago, Wikipedia has removed Flyspray because no stable version and CVEs:
- https://en.wikipedia.org/wiki/Flyspray_(bug_tracking_software)
- https://en.wikipedia.org/wiki/Bug_tracking_system
- https://en.wikipedia.org/wiki/Comparison_of_issue-tracking_systems
- https://en.wikipedia.org/wiki/Comparison_of_project_management_software
- https://en.wikipedia.org/wiki/Template:Bug_tracking_systems

Time to solve it?

**Comment by Neustradamus** [comment]
@jahto, @Psychokiller1888: Flyspray 1.0 RC11 is out!
- https://github.com/flyspray/flyspray/releases/tag/v1.0-rc11

Time to update your version ^^
Please do a backup before.
Please inform if it is good for you or if you have a problem.
