### ISSUE TITLE
make (project_id,version_name) unique in table list_version

### ISSUE THREAD

**Issue by peterdd** [Flyspray/flyspray#102]
It seems it is possible to insert 2 same version_name on a project. 
Can someone address this?

**Comment by peterdd** [comment]
similiar also for this tables:

list_os
list_resolution
list_status
list_tasktype

But not list_category, as it is a hierarchy, where same category names on different subtrees can be valid. 
(project_id,category_name, lft, rgt)

**Comment by Psychokiller1888** [comment]
There can be the same OSes in two different projects, so the columns can't be unique. Core side we could check if the project already has a same named os listed etc etc etc

**Comment by peterdd** [comment]
Thats why the project_id with *_name are grouped together in one unique key.... 

like 

UNIQUE KEY `keyname` (`project_id`,`version_name`)

**Comment by jahto** [comment]
I fulle agree with peterdd. Some tables really should have unique keys or indexes on project_id and some suitable field(s). I'll have my proposal for fixing flyspray-install.xml ready within 24 hours, so at least new installations will not suffer from duplicate entries. But upgrading existing ones that may already have them... I think those installations must just be manually fixed.

**Comment by Psychokiller1888** [comment]
Upgrade engine should check and not duplicate them no?

**Comment by jahto** [comment]
Upgrade engine does not add anything to those tables. My unfortunate experiences of getting a mistake already made fixed are that it's really hard and almost always ends up needing to manually update some tables.

**Comment by peterdd** [comment]
On the case that the upgrading would reveal such circumstances, the upgrade engine should stop before doing any upgrade processing and tell the dude/admin that he should resolve the existing conflicts by editing the colliding entries before upgrading.

**Comment by Psychokiller1888** [comment]
The upgrader should have  table schema, and a data schema as well and generate a diff in order to upgrade. It's doable, we do that in java for another project I work on. BUT, it's not me that implemented it, so I'm not fully aware of how it works, and the project is over 2m lines

**Comment by jahto** [comment]
I think I could have method 1 written and ready during thursday or at latest on friday.

**Comment by peterdd** [comment]
Great!
I will focus only on that csrf and cookie things now, you guys do the other stuff.

**Comment by jahto** [comment]
That was the whole idea, because I really can't help with crsf and cookie things. It's called "resource distribution planning" or something like that.

**Comment by jahto** [comment]
This can probably be closed, done.
