### ISSUE TITLE
oauth third party vendor bug?

### ISSUE THREAD

**Issue by peterdd** [Flyspray/flyspray#103]
I was just testing the oauth stuff with github oauth..

Lol, I fixed an occurring error message by renaming that file

vendor/league/oauth2-client/src/Grant>cp AuthorizationCode.php Authorizationcode.php

So this seems to be a third party bug?

A quick workaround could be 
in scripts/oauth.php line92

#$token = $obj->getAccessToken('authorization_code', array('code' => $_GET['code']));
$token = $obj->getAccessToken('authorization_Code', array('code' => $_GET['code']));

but what if the League\Oauth2 updates their code?

I have no experience with oauth or composer stuff, so could someone please check the best way to fix it?

**Comment by peterdd** [comment]
Maybe a php 5.3 vs php 5.4 issue, as newer versions are php5.4+ only of this oauth lib. The bug was fixed in nov 2014 , but the current version require php5.4....
So the composer just go back until it finds a version of the oauth client that fits php5.3.*?

**Comment by Psychokiller1888** [comment]
Yep... I wouldn't touch that, as third party will update and fix bugs... That's the whole damn problem with that composer... And to make FS user understand they have to run composer upgrade...

**Comment by peterdd** [comment]
And the commandline has php5.3.3 and the apache php5.2.17 on my hosting env...

hello dependency/version hell?

**Comment by peterdd** [comment]
I now switched to php5.6 in my hosting env and this bug in gone.

**Comment by Psychokiller1888** [comment]
Cool... Was wondering what was wrong, as I tested them and they were working... I bring that up again, but composer needs to be handeled...

**Comment by peterdd** [comment]
Do you think it is possible to handle that composer stuff on setup over the web?

So the user doesn't need a ssh shell (where possible different version of php is setup unlike the webserver/webspace)

**Comment by Psychokiller1888** [comment]
Would be possible. But the whole crap with this is that FS will have to handle "composer upgrade" as well, as the plugins continuously get developped and fixed... I don't know what to think about composer right now... I definitly know that if we leave it as it is now, we'll end up with thousands of people whining that FS doesn't work because they didn't understand/know about composer...

**Comment by peterdd** [comment]
If there is a stable combination of components found for Flyspray, we can nail that version into the composer.json .

My switch to php5.6 doesn't solve the problem for me as it is without support by hosting provider and has problems in other areas.

I opened an issue on the oauth2-client github project to fix it for php < 5.4.
