### ISSUE TITLE
Make the csv export table fields respect the user permissions and fields choosable like for task list

### ISSUE THREAD

**Issue by peterdd** [Flyspray/flyspray#110]
At least the user permissions should be considered for 1.0 release so users without permissions for some fields can't workaround that by just exporting the issues list. :-)

**Comment by Psychokiller1888** [comment]
Well, the only field would be effort tracking right? And I think it was handeled already?

**Comment by peterdd** [comment]
Moved the issue to bugs.flyspray.org as FS#2054 and FS#2055 .
