### ISSUE TITLE
Houston, we've got a problem (after merging pull request #111)

### ISSUE THREAD

**Issue by jahto** [Flyspray/flyspray#115]
And another one too. Previous versions on Flyspray seem to have been saving detailed task descriptions as plain text, mostly with as utf-8, although I have a few really old examples where the encoding is something else. Might be my own fault and mess with database default character encodind, might be something that depended on the browser used. 1.0 saves them with html tags added and characters like ä converted to html character entity &auml; and after that pull request merge I get back &amp;auml; when viewing task details... (github too might mangle this example totally incomprehensible).

First thing is to decide in what format the task descriptions are saved. If with html tags and encoding of characters, then the upgrader should convert existing entries and leave a flag in database that it has already done it, so it won't happen twice. If not, then something else must be done, like stripping all html tags and recoding html character entities to utf-8 when saving task descriptions.

**Comment by jahto** [comment]
Yes, github mangled my example. Check yourself what happens and look especially at the page source.

**Comment by Psychokiller1888** [comment]
I think utf-8 encoding should be used everywhere...

**Comment by jahto** [comment]
Those few cases where the encoding was not utf-8 are more than 7 years old, I've been using flyspray since 2005... You can highlight this problem by creating a new task with the detailed description "Mettre en évidence" and see yorself what happens when you save it.

**Comment by jahto** [comment]
Merge of pull request #116 just moved the problem to another place. Just open a new task with flyspray 1.0, put some accented characters do the detailed desciption, use ckeditors' formatting capabilities too, save it, go to the tasklist and hover mouse over the just opened task and you understand what I mean. I don't know what Dans' original problem was, but entries made with older versions of flyspray must be handled differently than those made with 1.0. Something like this works for me, what actually get's echoed and how it's escaped might have to be changed so Dans' problem won't reappear, and it needs 2 translation entries more:

```
<div id="desc_<?php echo $task_details['task_id']; ?>" class="descbox box">
<?php
 echo '<b>' . L('tascdesc') . ':</b>';

 if ($task_details['detailed_desc']) {
    if (strpos($task_details['detailed_desc'], '<p>') === 0) {
        // assume task description was made or edited in
        // flyspray 1.0 and is safe to show without Filters::noXSS.
        echo $task_details['detailed_desc'];
    }
    else {
        // old description made before upgrade, might contain
        // something that needs escaping.
        echo '<p>' . Filters::noXSS($task_details['detailed_desc']) . '</p>';
    }
 }
 else {
    echo "<p>" . L('nodesc') . "</p>";
 }
?>
</div>
```

**Comment by Psychokiller1888** [comment]
Well.... That's a pain... And I'm not really a big fan of if statements to keep old data runing correctly... To be honest I think the DBs should be upgraded to the new format and the code kept clean for one version only... What do you think?

**Comment by jahto** [comment]
That's an option too. I'll just have to find out what's the correct way to upgrade to the new format... It would help if Dan could send an example of a task description that causes him problems.

**Comment by Psychokiller1888** [comment]
Ihave asked him to take part in this convo.

**Comment by jahto** [comment]
Good idea. I really don't understand what's the problem, I haven't experienced it, but then I maybe just do not have those kind of entries in my test database. Which is a dump from production version before jumping to 1.0-dev and has approximately 1300 tasks in 17 projects collected over years. Enough material for testing, but missing just this one problematic case.

**Comment by jahto** [comment]
After investigating a little, I don't think it's related to those strange characters, but I found another issue. We need to play with ckeditors configuration. The default values break search. I tried with using characters ä, é and ů as detailed task description and doing advanced search for each one checking "Search details". With ckeditors default settings, ä and é got converted into html character entities in post request but ů not, so the search worked only for ů. I think the following patch would be the right solution, but I'm asking if there are other opinions before fixing it and making a pull request:

```
        //Activate CkEditor on TextAreas.
         $return .= "<script>
-                        CKEDITOR.replace( '".$name."' );
+                        CKEDITOR.replace( '".$name."', { entities: true, entities_latin: false, entities_processNumerical: false } );
                     </script>";
         return $return;
     }
```

**Comment by jahto** [comment]
Experimenting with converting already existing entries to the format that's used by ckeditor when it posts data back and so will became the new default format for some database fields. Something like the following seems to work, maybe needs some finetuning, character set detection do be done, should already be UTF-8 anyway on existing entries, comments from anyone? 
```
<?php

$data = "Data to be converted:
'Add a few single and double \"s

A few html tags too... what's already there probably can't be trusted to be valid.


<li>The next sentence is in finnish:</li>
<li>Tämä lause on suomea.</li>

";

// Add here some kind of detection of charset used, convert to UTF-8 if needed.
// echo mb_detect_encoding($data, "auto", true);

$data = htmlspecialchars($data, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
// Convert two or more line breaks to paragrahs, Windows/Unix/Linux formats
$data = preg_replace('/(\r?\n)+\r?\n/', "</p><p>", $data);
// Data coming from Macs has only carriage returns, and couldn't say
// \r?\n? in the previous regex, it would have also matched nothing.
$data = preg_replace('/(\r)+\r/', "</p><p>", $data);
// Remaining single line breaks
$data = preg_replace('/\r?\n/', "<br/>", $data);
$data = preg_replace('/\r/', "<br/>", $data);
// Remove final extra break, if the data to converted ended with a line break
$data = preg_replace('#<br/>$#', '', $data);
// Remove final extra paragraph tags, if the data to converted ended with
// more than one line breaks
$data = preg_replace('#</p><p>$#', '', $data);
// Enclose the whole in paragraph tags, so it looks
// the same as what ckeditor produces.
$data = '<p>' . $data . '</p>';
echo $data;
?>

```

**Comment by Psychokiller1888** [comment]
I gonna be very honest... I have to confess that i'm the worse possible guys to speak encoding with... I've always had problem understanding that part of informatic

**Comment by peterdd** [comment]
Html character entities in detailed_desc should be avoided. (Unless in code-tag section for example where it can be part of a code bug description)
We use utf-8 everywhere now and it probably would change  the search results for text in detailed_desc.

What subset of html we want allow task editors to make it harder to break or insecure flyspray installs.
How is validity of this html is enforced so no bad mixed htmltagsoup is stored in detailed_desc.
When,why and by whom was the switch from dokuwiki syntax to html was made.. (csv,svn,git...)

**Comment by jahto** [comment]
I wish I knew the real answer to your last question... Probably when ckeditor was put in use. And I think that the change to ckeditors default behaviour should be made now, so at least searching works. Maybe even change also entities: true to entities: false later. I really haven't thought about the possible consequences for that change yet.

**Comment by danoh** [comment]
Hello, right I am Czech, and I use the strange characters ;-)

I also don't think, that we have any troubles with accents, there is serious issue with displaying unescaped html content. So any user can attack other users by injecting javascript or iframes into task details. I met serious issue solved by my patch https://github.com/Flyspray/flyspray/pull/116/files, where the text used in javascript popup with task details description (in task list) broke whole site by unbalanced quotes, big part of the page was interpeted as javascript function parameter. I had to fix it in database, because I was no longer able to access the task. I have no longer the string which broke it, but I can probably made another demonstration example.

I agree, that we should avoid using html entities. But primary goal should be secure the content handling, it can cause serious troubles especially on public installs.

**Comment by peterdd** [comment]
@Psychokiller1888 : Don't worry, I knew at the beginning of unicode and that utf-xx stuff, that this will lead that some dudes get paid work for years, skin heads of programmers due pulling out their hairs and craziness.
*Lalalalalala jumping around*

**Comment by jahto** [comment]
Ok, now I understand better what the issue is. But using Filters::noXSSL also escapes the html and html entities that ckeditor produces when posting data back to the database. There seems to be also a function named Filters::noJsXSS, perhaps adding a third one, Filters::noJs could help in solving the problem. Or something else. I agree that secure content handling should be the primary goal, but making the popups almost incomprehensible to an average user who doesn't understand escaped html is not a good solution. We'll have to really think when and what data is going do be sanitized. In reality, any textual data coming in from users...

Did peterdd have one beer too much recently?

**Comment by danoh** [comment]
In the popup we can use plain text with limited length, so just remove all the tags and take the first ~50 characters.

BTW anyone from flyspray contributors is invited to czech pub, when comes to Prague.

**Comment by jahto** [comment]
I halfway agree, halfway not. Not with removing ALL tags and not with the limit being so low. It has already been very useful to see enough of the detailed description already in tasklist popups to decide whether it should be reacted on immediately or later without opening the task itself.

**Comment by Psychokiller1888** [comment]
.... We need a switch for the editor... From my mobil, that has JS enabled, the editor doesn't show up, and all the formatting tags from the default task desc are visible in the task detail box, as it's a simple textarea...

**Comment by jahto** [comment]
I'm beginning to understand the problem after manually modifying a task description to be the following:
```
<script type="text/javascript">function breaksite(e) { DokuWiki supports **bold**, //italic//, __underlined__ and 'monospaced'' texts.
Of course you can **__//'combine'//__** all these.
```
Dokuwiki formatting capability seems to also have been disappeared. For 1.1, it could might be restored. Have to read and understand https://www.dokuwiki.org/plugin:ckgedit first.

**Comment by peterdd** [comment]
For info: Dokuwiki project itself used Flyspray as bug tracker, but switched to github a year ago.
https://www.dokuwiki.org/bugs

**Comment by peterdd** [comment]
For reducing impact of (accidently possibility) adding malicious code into task details, there is the 
"Content Security Policy" feature, which tells modern browsers which parts of loading resources can be trusted and which should ignored/blocked. But this is a whole new feature and more of a second defense line.

**Comment by peterdd** [comment]
Same problem on HTML in comments...

I will look at how we sanitize HTML input in an strong and well tested, but easy to implement way.
The set of allowed HTML tags should be the HTML tags that the HTML output of dokuwiki is capable. 
(whitelisting)
Something like 'h1-h6,p,ol,ul,li,img,blockquote'.

The set of allowed HTML tag attributes should be also a minimum.
Maybe 'class, style', but maybe just allow no tag attributes. :-P

**Comment by peterdd** [comment]
includes/class.tpl.php TextFormatter::render()

 seems the intended way we should look at.

So there is only 'dokuwiki' plugin in source code, no 'none', or 'html' plugin?

**Comment by jahto** [comment]
You are exactly on the right track. And I share your thoughts about having a 'markdown' plugin later, been thinking exactly the same. Maybe there's already something in dokuwikis source that we too could use for sanitizing pure html input and output without the actual markup.

Should we already merge my changes in https://github.com/jahto/flyspray/tree/restore_dokuwiki_formatting so there would be someone else too to do some testing and getting it in for beta/release candidate release? That's not something I can handle alone.

**Comment by peterdd** [comment]
I made a pull request now which adds simple html sanitation in the case of missing syntax plugin.

well, I think the plugin formatter class isn't loaded, even if dokuwiki is configured as syntax_plugin.
Maybe your current work does it. So I hope my pull request is merged fast and you/we can 
finish that show stopper problem.

**Comment by jahto** [comment]
Exactly. Composer and autoloading broke the loading. And psycho is quite fast on accepting pull requests.

**Comment by peterdd** [comment]
Your branch updating dokuwiki adds 3700 files and 50000 lines? 
I would say no at this stage.
Could you please fix dokuwiki support with the code we still have in flyspray?
So only the small code fixes you made in the branch?

**Comment by Psychokiller1888** [comment]
Merged :)

**Comment by jahto** [comment]
I've got too branches, one for restoring the current funtionality (restore...) and another one (update...). I'm NOT suggesting that update one should be merged. Only the restore one, with small changes only to two files. But at some point in the future, the update too should be done, after weeding out everything unnecessary (if copying license allows it). According to history, it was last updated on november 2006.

**Comment by Psychokiller1888** [comment]
Status?

**Comment by jahto** [comment]
Ok. Update will be left to 1.1. Made some testing, made an evil task by manually inserting parts of libssh2.dll to detailed task description in database, couln't break anything.

**Comment by peterdd** [comment]
How it will syntax_plugin be handled on upgrader 1.0?
dokuwiki stays default for 1.0 installs?
Users who used a dev version keep ckeditor/html? What value do we set for syntax_plugin for them? Keep "none"?

**Comment by jahto** [comment]
I think "none" was the default in previous versions and it still is in 1.0 too. Although, "none" now means actually "html". But this was what it really meant in previous versions too. If I remember right, I could just write html tags myself to task description and comments. So in practice the situation does not differ a lot, we just have to not change current setting when upgrading.

**Comment by peterdd** [comment]
I wrote now Jordan and Psycho bringing up some sec issues we must take care.

I would recommend for new installs set dokuwiki as default in installer setup and let the user choose "html" at his own risk with a warning (for 1.0).

**Comment by jahto** [comment]
Dokuwiki is definitely safer for new installations, although our plugin is quite old. For 1.1, I WILL update it. Besides, there are a few newer dokuwiki plugins that can also handle converting between html->dokuwiki, dokuwiki->markdown and markdown->dokuwiki. Of course, both dokuwiki and any markdown implementations both handle perfectly well converting to html... Yes, you read me right, markdown support IS in my plans for 1.1.

**Comment by peterdd** [comment]
My only experience with markdown is here on github. As coder, I find it easier in dokuwiki to use the code-tags, while with markdown here I'm forced to use 4 spaces on each code-line. Maybe I oversee something?

**Comment by jahto** [comment]
I'm fine with both ones. GitHub uses a modification of markdown and that's the one I too planned to support in 1.1. Read https://help.github.com/articles/github-flavored-markdown/, you don't have to use 4 spaces, there are "code fences". And in the future, just let the user choose!

**Comment by peterdd** [comment]
Thanks! Enjoy your beer. :-)

**Comment by jahto** [comment]
I think this could be closed. Dokuwiki formatting works. The rest of ideas thrown in the air here should be added to our own bug database as feature requests before closing.
