### ISSUE TITLE
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

### ISSUE THREAD

**Issue by Schengawegga** [Flyspray/flyspray#12]
If i try to leave a Comment or an Update and have other User to notificate, this error will appear: "Completely unexpected exception: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. This should never happend, please inform Flyspray Developers"

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
