### ISSUE TITLE
flyspray.org - Page Not Found

### ISSUE THREAD

**Issue by CaioCesarDev** [Flyspray/flyspray#120]
Hello,

I am trying to access the page to see the documentation, but I can not, what happened to the page? D:

**Comment by jordanmendler** [comment]
We are working on it as we transition over the new site


________________________Jordan Mendler
[image: The Veloz Group]
The Veloz Group
President & Chief Technology Officer
jordan@thevelozgroup.com
www.thevelozgroup.com

**Comment by CaioCesarDev** [comment]
Cool! therefore I will wait ...
thank you! @jordanmendler

**Comment by jordanmendler** [comment]
Should be fixed now!


________________________Jordan Mendler
[image: The Veloz Group]
The Veloz Group
President & Chief Technology Officer
jordan@thevelozgroup.com
www.thevelozgroup.com

**Comment by Neustradamus** [comment]
I have done a new ticket about the down/dead website since several months:
- https://github.com/flyspray/flyspray/issues/829
