### ISSUE TITLE
lost oauth config on upgrading dev->master

### ISSUE THREAD

**Issue by peterdd** [Flyspray/flyspray#121]
I tried the upgrade script on my dev setup with latest master. It seems I lost my testing github oauth setup in flyspray.conf.php

Before that I just unzipped the github master zipfile over my testing version.

The upgrader needs the user give a feedback from the upgrading process.
In the best case a dry run information what will be added/changed if the user starts the real upgrade.

Currently I don't understand what happened with the config by upgrading..

**Comment by Psychokiller1888** [comment]
Well, I just moved the active oauth list out of the conf file to make it accessible in the admin pannel. Added, for public, the MS one, and gave default links for them so users won't be asked all the time what the redirect link is on FS. So dunno, maybe that last part overwrote them?

**Comment by peterdd** [comment]
I made quick fixes on upgrader and upgrader default config. Please review, just a hack to have some working for me. I think we need some info how to setup oauth in admin area, but please no more adding features for 1.0 or we never release 1.0. Maybe make oauth stuff complete configurable in fs 1.1 or later.

**Comment by Psychokiller1888** [comment]
I wanted to leave oauth secret and ids into config file... Dunno, why not move that to admin as well...

**Comment by Psychokiller1888** [comment]
I consider this as made. Adding full oauth will be for 1.1, end of year
