### ISSUE TITLE
Bring back dokuwiki formatting.

### ISSUE THREAD

**Issue by jahto** [Flyspray/flyspray#126]
1.0 broke it. Ok, I already opened a new branch restore_dokuwiki_formatting on my development machine and will start working on it. Might as well upgrade dokuwiki plugin itself.

**Comment by jahto** [comment]
Let's not update dokuwiki plugin. Too much problems. Restoring old functionality seems possible.

**Comment by jahto** [comment]
I actually could make also updating dokuwiki work, but with 3763 files changed or added it's a bit too big change to be made just now. Maybe later... after checking that it actually work, currently all I can say is that it didn't immediately crash everything after a few changes, saving tasks and previews actually worked, one oddity was that words that should have been underlined changed to italics. Probably more such oddities surface after further testing.

But restoring the old dokuwiki to working state is in my opinion a must, because it really worked in 0.9.9.7. Tested myself.

**Comment by peterdd** [comment]
If it worked in the last official release 0.9.9.7 we can't just drop dokuwiki support if there is no superior better AND safe, and upgradable and also downgradable solution available.

I personal never was a big fan of wiki syntax (many wiki software invented there own flavor), but having dokuwiki is/was a much safer way of letting user make extended task descriptions than allowing HTML, which is no easy task to validate and enforce only accepted tags. There are soo many weired tricks in the wild how to pass HTML sanitization, you will not believe until u have seen. 

As example how hard it is: Image a brave user wants report a piece of maliciuos code as example to flyspray. How the system can distinguish it from a real attack? Looking for

    <code>.. maliciuos code ... </code>

But what if the maliciuos code tricks us to break out of the code section and it gets accepted. Later a browser on user side tries to fix bad nested HTML and executes the malicious code.

**Comment by jahto** [comment]
I see getting dokuwiki working once again and preventing malicious code both from getting into database and then output back to the user as two separate issues. Flyspray never was good at the latter one, as Dan can confirm. Fortunately, it's also not exactly a previously unknown issue or something that wouldn't have some at least acceptable solution available that we could maybe borrow. Just have to find it... It might take for a while, and between thursday late afternoon and saturday early afternoon I'll have a little less time to use for Flyspray. A significant other one comes visiting from another city, we'll probably have a little/lot of wine and beer, and enjoy time together.

**Comment by peterdd** [comment]
I for myself will try to find the last candits in code for tpl_form and as easy task find missing translation strings for the 1.0.
All my further plans for enhancement flyspray are postponed to Flyspray 1.1 or later.

I have currently no solution how we can handle or avoid composer related issues.

I think, either someone has to dig deeper into composer and its advanced configuration and how this can be integrated also into automated continuous integration test on github/travis-ci.
So we get immediatly informed if some software setup combinations brake, because a third component isn't compatible with Flyspray code anymore.  

Or... i don't know...

**Comment by peterdd** [comment]
and @jahto: Enjoy your real life time and don't brake your laptop ;-)

**Comment by jahto** [comment]
I think I will still have enough time tomorrow to do some testing and present my own list of candidates for using tpl_form. Either I'm getting back 'missingtoken' or the button just doesn't look the same as those near it or in one case, it's even not a button but an ordinary link (edit comment).

**Comment by peterdd** [comment]
Yeah, I have some tpl_form fixes done in my branch, but this branch reverts also the noXSS for task description and I don't want an edit war with @danoh or other devs. 

I hope we get a solution together with @jordanmendler and @Psychokiller1888 soon.
( @danoh, @jordanmendler, @Psychokiller1888 or any other interested in 1.0 release please comment too on this topic.)

**Comment by Psychokiller1888** [comment]
I'll be back in busness tomorrow, my wife leave for Finland tomorrow, spending last evening together for a month

**Comment by peterdd** [comment]
@jahto: You can merge my current branch to your own branch if you want test my changes.
@Psychokiller1888: Have a nice evening

**Comment by jahto** [comment]
Ok, I'll do it before beginning testing. No use to report something you already know.

**Comment by jahto** [comment]
One oddity with dokuwiki support. Could peter who actually understands this kind of things have a look at it before going beta? It's probably related to either css, my browser or dokuwiki formatting being really old style.

I made a comment entry that shows up in database as `"**Let's** //try// __this__ one."`. When pushing preview button (which seemed to be workingI, I got back what I was expecting. But after saving it, it shows line breaks after each word. No line breaks or other formatting changes in database, and page source code is:
```
    <div class="comment">
        <div class="commenttext">
      
<p>
<strong>Let's</strong> <em>try</em> <em class="u">this</em> one.<br />
</p>
</div>
                </div>
```

**Comment by peterdd** [comment]
Which git branch version did you used, so I can test your issue?

**Comment by peterdd** [comment]
and did you set syntax_plugin to dokuwiki for testing?

**Comment by peterdd** [comment]
If you want test the appearence of a page in different browsers and browser versions I suggest 
http://browsershots.org/ where is one test free per day or something like that.

We should use it when testing and making the last polishing for the release.

**Comment by jahto** [comment]
Latest master from upstream, and OF COURSE I had dokuwiki syntax turned on. I just don't get it what's happening, because everything seems to be right and as it should.

**Comment by peterdd** [comment]
Sorry for my real stupid question. :-) 
Ok, I will take a look. 

For finding the root of HTML/CSS display issues I suggest using the builtin debugging features now integrated in all modern browsers. Often accessible by just pressing F12.
I'm used to the Firebug Extension of Firefox, who is a daily tool for me at work.

**Comment by peterdd** [comment]
That was an easy catch:

In theme.css :

    div.comment_container .commenttext em {
    display: block;
    .....
    }
    div.comment_container em {
    display:block;
    .....
    }

em-tag is by default an inline element. I don't know why someone wanted it a a block element. Yesterday I removed a surrounding em-tag around the whole comment display in template which I see no real benefit for. Maybe this rules were made for this em-tag. But they forgot someone input em-tags into as html or its syntax in dokuwiki format. :-) 

I suggest removing that both css-rules for that em in theme.css completely.

**Comment by jahto** [comment]
I trust that this issue will be in good hands and handled by a person who actually knows what he's doing on that area, will logout now from github and continue to have a few glasses of wine with a significant other one. I'll look at some parent/subtask related issues on sunday, unless something more urgent surfaces.

**Comment by peterdd** [comment]
@jahto: As you are reviewing dokuwiki plugin: There are this 5 deprecated split() calls in dokuwiki plugin: 

    plugins/dokuwiki/inc/pageutils.php:334:    list($page,$hash) = split('#',$page,2);
    plugins/dokuwiki/inc/common.php:644:  list($from,$to) = split('-',$range,2);
    plugins/dokuwiki/inc/common.php:845:    $df  = new Diff(split("\n",rawWiki($id,$rev)),
    plugins/dokuwiki/inc/common.php:846:                    split("\n",rawWiki($id)));
    plugins/dokuwiki/inc/HTTPClient.php:253:                list($key, $value, $foo) = split('=', $cookie);

Replacing by explode() should do the job, but I didn't looked into the source context.
These are the last places, whose replacment is a requirement for 1.0, look FS#1174.

**Comment by WooterTheTroubleshooter** [comment]
How about adding Markdown support?

**Comment by peterdd** [comment]
Yea, we had yesterday the same idea. But not in the coming release 1.0. We try to make all the existing features stable now. There are some old in production flyspray installs that use dokuwiki syntax und we want a smooth upgrade.

But the current architecture of Flyspray allows the adding of other syntax plugins. So markdown may be an option for future releases. But switching the markup in existing installs shouldn't result in garbage, so let's say Flyspray 1.2 or later if there is huge voting for that.

**Comment by jahto** [comment]
Just a note: I found one really important user of dokuwiki formatting. It's bugs.flyspray.org. I guess I'll have to do a little bit more testing...

**Comment by peterdd** [comment]
We shouldn't invent our own wiki<->html converter rules.
There can be something found on dokuwiki page itself if you search for html2wiki or wiki2html.

And this looks also promising, although its written in Perl (but the rules there shouldn't be to complicated to port to php):

http://search.cpan.org/~diberri/

Maybe we just do it as Filter? So we can convert on upgrading dependend on existing entries and future description formats.

    $out=html2dokuwiki($in) and 
    $out=dokuwiki2html($in)

    $out=wiki2html('dokuwiki', $in);
    $out=wiki2html('markdown',$in);
    $out=html2wiki('dokuwiki', $in);
    $out=html2wiki('markdown',$in);

I talked today with a guy of a big company. They use redmine extensively and they also use a wikilike syntax there.

My personal experience with wysiwygeditors in CMS Joomla, Drupal and Wordpress is, that nontechnical peoples try to copy their in MS word written stuff into this fields. Then often it was my boring job to clean that mess by deleting htmlcode >90% garbage. 
The dokuwikibuttons help in understanding and people can quick learn and adapt to the syntax.

**Comment by jahto** [comment]
My idea was not to convert dokuwiki formatting, only those flyspray databases and installations where no formatting at all was used. It could be useful for some advanced users who have the time to inspect their database and make sure it's not going to break anything or the user can tolerate it if something breaks. A bit like mass operations on tasks. Lets leave it in disabled and and make a note somewhere. Personally, I'm going to use it.

Sometime in the future, a Filter might be a good idea, it could also enable changing the formatting after installation.

**Comment by jahto** [comment]
I think this could be closed. Dokuwiki formatting works. The rest of ideas thrown in the air here should be added to our own bug database as feature requests before closing.
