### ISSUE TITLE
not working preview button at index.php?do=admin&area=prefs

### ISSUE THREAD

**Issue by peterdd** [flyspray/flyspray#128]
got no content back from callbacks/getpreview.php

and a 404 Not Found - themes/CleanFS/ajax_load.gif

Both no big problems, can also be fixed later...

**Comment by jahto** [comment]
Some additional notes on buttons etc., made when logged in as a Project manager:

When vieving task, "assign to me" -button looks different from the other ones. Also, when it's visible, the layout of buttons on the right side of the page breaks.

"Add me to assignees", got back "missingtoken".

"Re-open this task", got back "missingtoken".

Quick actions, "Make this task private" doesn't do anything.

"Preview" -button should not be shown unless dokuwiki formatting is in use. CKEditor already is in preview mode and has a itself a button to switch it into "code" -mode. Dokuwiki editor has a separate preview mode, and worked (in my branch for restoring dokuwiki).

"Reset" -button when editing a task description does nothing. Can be left out, user gets almost same functionality by not saving the task.

"Remove" should not be shown when adding a comment until there's already an attachment added that can be removed and should also be a button.

The same with "Add another link".

"Edit" for editing a comment should also be a button.

A lot of things to fix. Some critical, some not.

**Comment by peterdd** [comment]
> When viewing task, "assign to me" -button looks different from the other ones.
Just a CSS problem: a-tag class="button" are white, button-tags are blue. can be fixed on css/theme overhaul.

Fixed ~~ Also, when it's visible, the layout of buttons on the right side of the page breaks.~~

Fixed ~~"Re-open this task", got back "missingtoken".~~

> Quick actions, "Make this task private" doesn't do anything.
Seem this was never implemented at that position...

Done ~~"Edit" for editing a comment should also be a button.~~
But the comment box div be redesigned ....

**Comment by peterdd** [comment]
Fixed ~~"Re-open this task", got back "missingtoken".~~
Now Implemented ~~Quick actions, "Make this task private" doesn't do anything.~~

**Comment by peterdd** [comment]
"Remove" should not be shown when adding a comment until there's already an attachment added that can be removed and should also be a button.

I think this is just for reducing the amount of multiple upload input field. So the function is ok. Yea, maybe make it a button too, maybe a remove-icon would do also th job (with title attribute for L('remove'))

The same with "Add another link".

Does anybody know the reason or function of "Add another link"? I don't understand what a user should add here. A FS# task id? A website link? All that can be done in the comment text too.

**Comment by jahto** [comment]
It's not really critical if it shows or not, leave even thinking about implementing that one for 1.1. But it would be nice have it looking prettier, remove-icon is a good idea.

I think the whole idea of having links as a separate feature was not well thought, because as you say, they can be added in the comment text. What I know is that when I tested that feature, I had to immediately fix it, because one column name in database didn't match what was used in code. Might as well have just commented out the whole thing, whoever wrote it didn't bother even once to test it, and it doesn't seem to have been used by anyone using 1.0 dev, no bug reports. But then of course, it's always nice to have "Reference links:" and then a list of them separate from the comment itself...

**Comment by peterdd** [comment]
Mmh, flyspray_links looks like this here on my Mysql: 
show create table;

    CREATE TABLE flyspray_links (
    `link_id` int(11) NOT NULL AUTO_INCREMENT,
    `task_id` int(11) NOT NULL DEFAULT '0',
    `comment_id` int(11) NOT NULL DEFAULT '0',
    `url` text COLLATE latin1_german1_ci,
    `added_by` int(11) NOT NULL DEFAULT '0',
    `date_added` int(11) DEFAULT '0',
    PRIMARY KEY (`link_id`),
    KEY `task_id_links` (`task_id`)
    ) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_german1_ci

Shouldn't it better looks like this:

    `task_id` int(11) DEFAULT NULL,
    `comment_id` int(11) DEFAULT NULL,

and indexing, one on task_id, on index on comment_id ?

Comment out comment links and task links for 1.0? What are use cases for that feature? Currently it clutters the interface without function.

**Comment by Psychokiller1888** [comment]
I think the whole idea behind this is that teams working together can add external links about the task. The table is maybe made this way so that you can see on task who added what link and when it was added... If usefull or not? I actually don't know...

**Comment by jahto** [comment]
I really don't know either. It seem's to have been added when pull request #49 was merged by Arborwave on 07.08.2014, and the exact commit thad adds this feature says only 'merged teng's work'.  Who is Teng? Maybe we should ask about this one from Arborwave.

**Comment by Psychokiller1888** [comment]
I'd say, we comment it out, and plan it for 1.1 back in, in a more integrated way, if needed. What do you guys think?

**Comment by jahto** [comment]
I've got a hunch that teng might be someone from Jordan's company, he could put a few guys working on things on summer 2014 and this might be a feature he actually needs, just not really finished. Let's ask him before making the decision to comment it out.

**Comment by peterdd** [comment]
Maybe it was an attemt to list/find links in a structured way in tasks. And checks if the still work or are HTTP404. 

All that can be made also if the links are in the task description with small more effort on filter the links from task desc.

I think the 2 buttons add attachment and add link should be not on top of the edit comment field.

Either integrate them within the dokuwiki or ckeditor bars or somewhere beside or unter the comment field. But can be done in 1.1.

**Comment by peterdd** [comment]
"Reset" -button when editing a task description does nothing. Can be left out, user gets almost same functionality by not saving the task.

It works on the raw textarea without js enabled, but not with ckeditor running. ckeditor has its own back/forward buttons.

Maybe move the reset to the line above the textarea and make it smaller. Removing it could maybe annoy a user who made changes on the many other fields and then in the last step garbled the task description accidently.
