### ISSUE TITLE
Massop rework

### ISSUE THREAD

**Issue by peterdd** [flyspray/flyspray#130]
The massop close doesn't respect open subtasks!

You can close a parent/supertask but the subtask stays uneffected.

Deactivate massops feature in source code for 1.0 and leave it for 1.1 or later?

Probably same problem on blocking/dependend tasks.

Mass operations must be IMHO handled by a real SQL transaction, where in case of an error in middle of processing a rollback can be done.

A poor mans solution - where real sql transactions aren't possible/enabled - would be to check all the possible dependencies of a mass operation and do the whole database operation only when there are no conflicts.

Also the movement of parent tasks to another project shouldn't be possible if there are subtasks.
Also the movement of sub tasks to another project shouldn't be possible if there are parent tasks.
Also the movement of tasks with dependencies shouldn't be possible to move to another project.

**Comment by jahto** [comment]
I'll can try writing some SQL on the next week, I'm pretty good with that one. I'f I don't get it finished in time, let's deactivate the whole feature and leave it for 1.1. Seems there will probably be 1.1 quite soon, after we get the features deactivated for 1.0 working and have fixed all the bugs that will get reported when 1.0 is released.

I don't totally agree with the last sentence. I already have actually one big project, but which is in reality splitted into 4 different projects depending on the component within the whole system, dependencies often occur between them, users file bugs to wrong project, dependencies get added and then later we realize that the bug report itself should be moved to another project. Subtasks and parents should all belong to the same project, not always the same with dependencies. Like I can't implement a feature or fix a bug in a user interfacing program written in C# in one project until I've changed something in another program written in Java in another project that feeds data to a database.

**Comment by peterdd** [comment]
I didn't knew until now that moving tasks between projects is a feature and is in use. My sentences were more quick type of reminder. If u use that feature u can do that work for 1.1+.

Transactions need higher hosting requirements, needs discussions, maybe mysql table changes, critical stuff that cant be done now for fs1.0

**Comment by jahto** [comment]
Yes, moving tasks between projects is a must to have. But I also agree that parent and subtasks should belong to the same project. No such relationship necessarily between dependent tasks, as my example shows. Parent and subtasks is a new feature in flyspray, I think the code just creeped in without any further thinking. I'll think about this one. Maybe move all subtasks on any level belove a parent if that's the one moved, prevent moving any subtask by itself and make sure that tasks belong to same project when creating the relationship.

**Comment by peterdd** [comment]
Let's deactivate massop for FS1.0 with a simple

    $massopenabled=0;

....

    if($massopenabled){
        /* massop stuff */
    } else{
        return L('massopdisabled'); # or just return an error, look source code how best do it
    }

on the massop handler and show L('massopdisabled') on the massop toggle form.

User who need it can activate it at their own risk. E.g. users who doesn't have subtasks or task dependecies in their Flyspray. Instructions how to reenable massops can be done in L('massopdisabled') translations.

**Comment by Psychokiller1888** [comment]
Yeah, turn it off for now

**Comment by peterdd** [comment]
massopsdisabled done. Please rename this issue and label it for later flyspray versions.
