### ISSUE TITLE
create REST API

### ISSUE THREAD

**Issue by skironDotNet** [Flyspray/flyspray#133]
Create REST API layer, so I could create Android client. Actually I could do the REST, but I don't have time :) 

I don't have time to create Android client either, but mentioning both is a good start.

Thanks,

**Comment by peterdd** [comment]
Not at the moment. You can add the feature on bugs.flyspray.org or vote for a feature there.
Currently feature freeze and all effort is going into releasing a stable 1.0.

Hopefully release candit mid of march and 1.0 release end of march I hope.

**Comment by Psychokiller1888** [comment]
Total freeze mid march, among with alpha
Beta 1st of april
RC after that, end of april release v1.0
