### ISSUE TITLE
Quick actions button

### ISSUE THREAD

**Issue by Psychokiller1888** [Flyspray/flyspray#138]
@peterdd When clicking it, it nicely opens the menu. But you can't close this menu... Not even by clicking outside of it. I think we should rather use a hover for this, what do you think?

**Comment by peterdd** [comment]
No, a second click on the quick action button closes it. 
You have no hover on normal touch devices.

The quick action button must always by visible, the quick action menu should not overlay the quick action button.

I would like to fix that issues, but first the tag structure must be in a good shape for applying the css later.

**Comment by Psychokiller1888** [comment]
Well, unfortunately, once clicked, there's no button anymore... I guess that's the issue you're talking about? Hover on touch devices produce the same effect as clicking on it

**Comment by peterdd** [comment]
We have currently two "quick action" things the left vertical bar and the quick action menu.

And we have huge white space in the center on a fullhd display.

And only if you scroll down you see all that nice features of the tabbed area.

**Comment by Psychokiller1888** [comment]
http://hpics.li/be49712

**Comment by peterdd** [comment]
the fact that the quick action menu overlays the quick action button is a bug.
Someone changed there...

**Comment by peterdd** [comment]
Let me first fix the structure on details view page. It contains invalid nested html currently. I fix that step by step.

**Comment by Psychokiller1888** [comment]
Sure np, thought posting it so it doesn't get forgotten and I know  you're working on the css  part so...

**Comment by Psychokiller1888** [comment]
Danke schön!
