### ISSUE TITLE
Upgrade didn't create "user_emails" table.

### ISSUE THREAD

**Issue by DynamicBits** [Flyspray/flyspray#18]
I upgraded from 0.9.9.7 to the latest code in the master branch as of 2014-01-01 (latest commit: 1e84126fd664f638260c451de67e04a270472cea). I did not encounter any error messages during the upgrade.

Aside from a few PHP warnings, the pages appeared fine. However, when I tried to log in, I got the following error:
```
Query {SELECT id FROM `flyspray_user_emails` WHERE email_address = ?} with params {} Failed! (Table 'myflyspray.flyspray_user_emails' doesn't exist)
```

I checked in MySQL, and the table certainly doesn't exist.

The server is running PHP Version 5.4.20.

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
