### ISSUE TITLE
Download impossible

### ISSUE THREAD

**Issue by alve89** [Flyspray/flyspray#184]
When I try to open http://www.flyspray.org/flyspray-0.9.9.7.zip a 404 GitHub error is shown. Could anyone please fix this?

**Comment by Psychokiller1888** [comment]
@jordanmendler Please tell me you still have the archives... I don't have access to the files, so I can't fix that

**Comment by jahto** [comment]
See https://bugs.flyspray.org/task/1974, I had it available, fetch it from there if needed.

**Comment by alve89** [comment]
Thank you!


Mit freundlichen Grüßen / Yours sincerely
Stefan Herzog

**Comment by Psychokiller1888** [comment]
Thank you! Fixed on
http://www.flyspray.org/docs/download/
as well

**Comment by jahto** [comment]
alve89, please note that we will release 1.0 alpha tomorrow monday. You might want to start with that one if you have not used flyspray before. But note also that it will inevitably contain also bugs along all the new features...

**Comment by alve89** [comment]
Can I already see what the new features are? And because I'm not sure which discussion is the right one: Is there (or already) a feature to report a bug via Email?

**Comment by Psychokiller1888** [comment]
This feature wasn't implemented no, not yet, will be for 2.0 maybe.

You can have an overview of the alpha new feature by browsing https://bugs.flyspray.org/ be be aware that it is also still running an old version.

**Comment by alve89** [comment]
Great, thanks. Is there (already) an API to create new reports? I often sit in my car and have new ideas I'd like to save as a feature request. I have the possibility to send a sms to my provider and it's forwarded via HTTP-POST to any file on my server. Can I read this array out and create a new request (automatically)?

**Comment by Psychokiller1888** [comment]
You're welcome. As said this will maybe be part of 2.0

**Comment by alve89** [comment]
Ah, okay, I thought only email-piping (or mailbox polling) will be a feature. Both API and email are already request (if I remember correctly), so I won't drop a new one.
Thank you!

**Comment by Psychokiller1888** [comment]
You're welcome!
