### ISSUE TITLE
FR: Select box in 'new dependency' form

### ISSUE THREAD

**Issue by alve89** [Flyspray/flyspray#186]
Because no one should be forced to remember the FS# you could bring a select box with all open FS to let the developer select the FS manually by title.

**Comment by Psychokiller1888** [comment]
Please, use bugs.flyspray.org for feature requests.

The idea is good, will be implemented for 1.1 I guess

**Comment by alve89** [comment]
I wanted to use bugs.flyspray.org but I'm not able to sign up or make a bug report anonymously. Where can I do this?

**Comment by Psychokiller1888** [comment]
Using the login and then registration form on the top right corner

**Comment by alve89** [comment]
Oh god, I'm blind. Sorry. 😄
