### ISSUE TITLE
Feature freeze

### ISSUE THREAD

**Issue by Psychokiller1888** [Flyspray/flyspray#192]
As promised, we freeze the sources. By feature freeze, I mean there won't be any new feature additions before Flyspray 1.0 is released.

Seing that we still have a couple of problems, I won't pack alpha right now, but as soon as the few opened points are reviewed.

Please do update you language files and create a pull request for them if you want them to be partof FS 1.0 alpha.

Once again, thanks everybody for the work accomplished for the release of Flyspray 1.0

**Comment by Psychokiller1888** [comment]
Organisation will be as follow:

- Semi stable alpha will be released asap
- 2 weeks after alpha release, and thus the users reported bugs fixed, we'll release a Beta. Alpha will not be updated.
- Beta pack will get updated if bugs found, and repacked for a week or two.
- First RC out and if users reported bugs are equal to 0, i'll pack 1.0 and release it.
- Master  will be branched so we keep a 1.0 trace right when beta comes out. So we can work on both

**Comment by Psychokiller1888** [comment]
We are live:

http://www.flyspray.org/docs/download/

**Comment by peterdd** [comment]
What happened to the old wiki? is there an archive? 
Can we download older releases for doing upgrader tests?

I even have an active 0.9.7 (not 0.9.9.7!) install (as CMS Joomla extension) from ~2004 which I want upgrade to 1.0 on the stable 1.0 release.
