### ISSUE TITLE
Effort

### ISSUE THREAD

**Issue by Psychokiller1888** [Flyspray/flyspray#195]
@jahto just deleted my whole thing, DB included, and tried functions. First bug, on task export:

Notice: Undefined index: effort in H:\GitHub\forks\flyspray\scripts\index.php on line 389

I'll drop everything I find here

**Comment by jahto** [comment]
I'll just comment it out. If the data used comes from Backend::get_task_list, effort might not have been fetched.

**Comment by jahto** [comment]
Ok, forget my pull request.

**Comment by Psychokiller1888** [comment]
Does that mean I quickly add it or you do something else and I should not?

**Comment by jahto** [comment]
5 minutes, I'll test if your fix is the right one. It probably is.

**Comment by Psychokiller1888** [comment]
No it's not a fix, it's an add, that doesn't fix the problem if you turn on the effort tracking

**Comment by jahto** [comment]
Yeah, came to the same conclusion. Done effort is not always fetched from database. Best to comment it just out.
