### ISSUE TITLE
Quick action and buttons

### ISSUE THREAD

**Issue by Psychokiller1888** [Flyspray/flyspray#218]
Again, i'm coming in hot for that...

But this: http://hpics.li/1d3592a

Is just not possible... I completly understand taht they are needed because of anti cross site protection and  god knows what... But buttons have nothing to do in a quick action menu... There is a simple workaround for it, using jquery you can craft links using POST instead of GET

And one more thing I just saw, the quick action menu, JS less now, doesn't close when clicking somewhere else, you need to click the button to close it again...

Speaking of buttons, the comments buttons for delete or edit aren't the same, we now have yet another button style, a very high and white one...

**Comment by peterdd** [comment]
1. Ok, will fix the css for the buttons now - if u spend me a club mate wodka sometimes. :-)

2. I understand u are used to that behavior. Old behavior probably can be reached also without js. 

3. the edit button can be justs a link, because it doesn't change data in the database. The delete must be a form with button instead. The layout of the 2 different button types can be merged into one layout.

**Comment by Psychokiller1888** [comment]
You're in Germany, let me know where, in less than 1 hour 30 minutes i cross the border, so i'll gladly pay you a vodka if you wish

**Comment by peterdd** [comment]
Not if u are sick and can't drink too. ;-)

**Comment by Psychokiller1888** [comment]
Wasn't thinking of driving out right now either... But in may/june we have to go to Berlin for some business with a friend, so if you're on the way, lemme know

**Comment by peterdd** [comment]
Dresden is not far away :-)

**Comment by Psychokiller1888** [comment]
Maybe not "not far away" but our way can go trough Dresden while on the way to Berlin

**Comment by Psychokiller1888** [comment]
"Old" behavior for the quick action menu can't be achieved using a simple :hover method and some css transitions

**Comment by peterdd** [comment]
I think it is possible for 'doesn't close when clicking somewhere else, you need to click the button to close it again...'

even if I'm not a big fan of it. But first the buttons...

**Comment by Psychokiller1888** [comment]
It's possible to make buttons look like <a> links actually

**Comment by peterdd** [comment]
yes.

**Comment by Psychokiller1888** [comment]
Bit better but now we have:
http://hpics.li/965d44a

Which is horrible looking... Well I guess i'll dive into the css

**Comment by Psychokiller1888** [comment]
So those buttons? Shall I drop the css part and do them or are you as you said on them?
