### ISSUE TITLE
@all: How many projects do you manage with Flyspray?

### ISSUE THREAD

**Issue by peterdd** [flyspray/flyspray#226]
1? 3? 10? 100? 1000?

Why do I ask?

I think many only manage 1-3 projects, but I think it is also possible to manage many projects like selling customized products to clients. And each custom product has its own project. (think of refurbishing an oldtimer over years, building home cinemas, a web agency managing many small customer web sites..)

And I'm now starting to make the komplex permission system easy managable for the user and want to know the average project count for creating the interface.

**Comment by PierreLvx** [comment]
At the moment, 9.

**Comment by danoh** [comment]
Hi, the biggest one is now its 25 projects, nearly 9000 tasks, 150 users.
