### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by anton-reutov** [Flyspray/flyspray#23]
When I try to login
i see this error

Query {UPDATE `flyspray_prefs` SET pref_value = ? WHERE pref_name = ?} with params {1393109327,last_update_check} Failed! (MySQL server has gone away)

PHP 5.4
MYSQL 5.5

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
