### ISSUE TITLE
Unable to set status of the task

### ISSUE THREAD

**Issue by danoh** [Flyspray/flyspray#239]
I made comment to this problem

https://github.com/Flyspray/flyspray/commit/9dfb3696c8f2c5ee975a1fd4c01f6692ba2ba4fa#commitcomment-10428598

**Comment by Psychokiller1888** [comment]
I think the idea here was that if you full edit a task, it's status goes back to new or unconfirmed. This isn't the case when you quick edit the fields. A changed problem usually doesn't have the same status anymore. @jahto I'm correct with your idea?

**Comment by Psychokiller1888** [comment]
Please use our bugtracker @ bugs.flyspray.org for further communications

**Comment by jahto** [comment]
Was it my idea? Don't remember ever changing anything related to task status. Must be a mistake.

**Comment by Psychokiller1888** [comment]
I think yes, I didn't change that. Anyway, it's changed now

**Comment by danoh** [comment]
Yes this is probably better. Just for info, my users are for years used to change in one step the progress to 100% and status to Waiting on customer. The new possibility with "click to edit" is fine, but generates two notifications instead of one in our case. But this is discussion for 1.2 or similar version.
