### ISSUE TITLE
php notice when viewing comments

### ISSUE THREAD

**Issue by anton-reutov** [Flyspray/flyspray#26]
when I look comments for task
I see php Notice

Notice: Undefined index: tasklist_type in /home/web/public_html/includes/class.tpl.php(128) : eval()'d code on line 85 Notice: Undefined index: tasklist_type in /home/web/public_html/includes/class.tpl.php(128) : eval()'d code on line 90

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
