### ISSUE TITLE
Admin user created, but not allowe to login

### ISSUE THREAD

**Issue by ddoddsr** [Flyspray/flyspray#27]
New installation of 0.9.9.7 on OSX running XAMPP

Was able to create admin user. I used the suggested password.
Tried to login after successful installation and got the message:
"That user does not exist on this Flyspray Installation"

repeatable 3xs

Reinstalled and noticed some messages in the pre-installation check

Library 	Status 	 
PHP >= 5.2.0 	Yes 	 
XML Extension 	Strict Standards: Non-static method Setup::ReturnStatus() should not be called statically, assuming $this from incompatible context in /Users/dandodd/PhpstormProjects/flyspray/includes/class.tpl.php(128) : eval()'d code on line 20 Yes 	 
SAPI (apache2handler) 	Strict Standards: Non-static method Setup::ReturnStatus() should not be called statically, assuming $this from incompatible context in /Users/dandodd/PhpstormProjects/flyspray/includes/class.tpl.php(128) : eval()'d code on line 25 Supported 	 
Database 	in PHP 	Flyspray
- MySQLi support 	Available 	Supported
- MySQL support 	Available 	Supported

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
