### ISSUE TITLE
Ability to make private/logged in only FlySpray installation?

### ISSUE THREAD

**Issue by arjitc** [Flyspray/flyspray#275]
Hello,
Is it possible to make a private / login only FlySpray installation? No issues would be displayed to guest/non-login users.

**Comment by peterdd** [comment]
Yes, there are settings per project for that. If you switch in every project settings
 "Allow anyone to view this project" and 
"Allow anonymous users to open tasks"  to off it should work.

![flyspray_private](https://cloud.githubusercontent.com/assets/1839154/7159777/d895c816-e384-11e4-896a-5b5a0130dd88.png)

at bottom
 
![flyspray_private1](https://cloud.githubusercontent.com/assets/1839154/7159778/de087a32-e384-11e4-9455-804add4b5217.png)

And drop most rights for the global default group (Basic) if you allow self registering.

I hope I add some more intuitive UI for setting and viewing permissions.

**Comment by arjitc** [comment]
Perfect this works! :+1:
