### ISSUE TITLE
Upgrading from a previous version to current not possible

### ISSUE THREAD

**Issue by michaelrice** [Flyspray/flyspray#28]
I am trying to upgrade from the last stable release: flyspray-0.9.9.7.zip to what is in github as of now on master. I get the following:

Warning: parse_ini_file(/var/www/flyspray/setup/upgrade/1.0/flyspray.conf.php): failed to open stream: No such file or directory in /var/www/flyspray/setup/upgrade.php on line 207 Warning: array_walk() expects parameter 1 to be array, boolean given in /var/www/flyspray/setup/upgrade.php on line 209

If you hit the upgrade button it says done, but wipes out the current config, and never updates the database.

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
