### ISSUE TITLE
Slowing down the developers

### ISSUE THREAD

**Issue by jahto** [Flyspray/flyspray#282]
It has been a very busy last three months trying to get 1.0 finished. Let's slow down now, actually think what we are doing and just fix important remaining bugs. The rest can wait.

Besides, gardening season begins here in Finland, so I'll be tending my garden on my free time instead of working with Flyspray unless it's a rainy day for the next 5 months.

Has been good working with you all, I'm beginning within the next weeks that slowing down, and let's start the discussion what 1.1 will be. I'm having some ideas....

**Comment by peterdd** [comment]
Here the tennis season is starting and I will have every weekend a league game or tournament next 2 months, - and training during week sometimes.

I will try to work a bit on flyspray to close the open 1.0 tasks, but not at the intense of the last months.

**Comment by peterdd** [comment]
summer ... :-)
