### ISSUE TITLE
IDEA: Flyspray in Node.js

### ISSUE THREAD

**Issue by nullivex** [Flyspray/flyspray#29]
Hey Guys,

I would just like to get everyones opinion and or interest in creating a node.js clone of Flyspray.

The project would keep the same philosophy and core concepts and then fix some of the set backs in our current Flyspray.

Then we would maintain the Flyspray 0.x branch as PHP and the Flyspray 2.x branch as Node?

Otherwise I was going to spin up another bug tracker project and clone node in Flyspray but I would sure like to see it get some love.

Personally, our department is moving away from any PHP apps and looking for alternatives in all departments.

Let me know guys!

Thanks

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
