### ISSUE TITLE
oAuth configuration issue

### ISSUE THREAD

**Issue by theozsnowman** [Flyspray/flyspray#298]
I have upgraded a 0.9.9.4 install to 1.0 and i found the upgrade tool did not write in the configuration for oauth to the conf file, so i have manually added it from what i found at https://github.com/Flyspray/flyspray/blob/master/setup/upgrade/1.0/flyspray.conf.php

I have set the urls in place for the YOURDOMAIN  comments in the conf file and github,google, facebook and microsoft are enabled in the admin 

I get the following sort of error however when i try and login using it

Completely unexpected exception: Config error make sure the microsoft_* variables are set.
This should never happend, please inform Flyspray Developers

now im a little confused what is missing in my configuration and also what the secret and id fields for each of these need to be set to?

can someone please clarify for me

TIA

**Comment by theozsnowman** [comment]
I actually found the issue was in league....

i updated vendor/league/oauth2-client/src/Exception/IDPException.php with the latest from Github and this appears to have resolved the issue

**Comment by peterdd** [comment]
I think the oauth config section should go into the prefs db table in future, so probaby nobody did take care of oauth upgrade in config file yet.

For e.g. using github as oauth provider you must register an app on github for your installation. You get github id and github secret from github, see https://github.com/settings/applications/new

**Comment by theozsnowman** [comment]
Thanks I have got it sorted :)
