### ISSUE TITLE
new task screen breaks in IE cleanFS

### ISSUE THREAD

**Issue by Sajaki** [Flyspray/flyspray#34]
the new task screen is broken in IE 11 using the cleanFS theme. everything is spaced wrongly and the round corners are gone. 

![capture](https://cloud.githubusercontent.com/assets/226730/3270032/20bf426a-f2fa-11e3-85b7-e9b6487ea659.PNG)

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Pelase reopen if issue still occurs
