### ISSUE TITLE
Non-ascii characters in new tasks leads to error

### ISSUE THREAD

**Issue by Thanatermesis** [Flyspray/flyspray#35]
I have tried to report a task in my flyspray install which included some strange (utf-8) chars in the description, they are from my terminal prompt, which looks like this:

~ ❯❯❯ howdy
zsh: command not found: howdy
~ ❯❯❯  

Then when i pick to create task and it triggers me an error in flyspray, like a creating-table debug entry, then I returned back, removed those special ">>>" chars and tried again which worked

So is there a bug that is unable to use utf-8 characters ? (which is very common in language characters)

Thanks

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Pelase reopen if issue still occurs
