### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by hhirsch** [Flyspray/flyspray#375]
If you reference an issue in a git commit it should add a comment to the issue.
This could be done with a git hook for example.

**Comment by peterdd** [comment]
Valid point, there still exists a similiar feature request: 
https://bugs.flyspray.org/index.php?do=details&task_id=1818

Feel free to vote for FS#1818 or do a comment there at bugs.flyspray.org 

ps: We want 'eat our own dog food' so only github related things here on the github issues.
