### ISSUE TITLE
move travis-ci integration from peterdd to flyspray master

### ISSUE THREAD

**Issue by peterdd** [Flyspray/flyspray#376]
I try to keep my master branch up to date with flyspray master, so the travis-ci button is also up to date. 
(Well, there aren't really tests written yet, but at least it looks cool to have a green button ;-) )

But this may not be always the time and it should be moved to flyspray master.

Either 
* jordan adds me to Flyspray organisation on github and I try to set it up for us
* or jordan does the webhook travis-ci setup

**Comment by Psychokiller1888** [comment]
Dude, use Skype group for contacting us... I'm planning a Skype meeting with all of us for a giant re organisation, so make sure to check the chat, vote for a date when I give them, and take part in the group call when defined. It most probably will be something like in 2-3 weeks, as soon as the work crazyness here goes down

**Comment by peterdd** [comment]
Finally jordan added the webhook for travis-ci and I could do the missing steps. Yippee!

And now somebody needs to write the boring tests...
