### ISSUE TITLE
Add Markdown syntax option for task descriptions

### ISSUE THREAD

**Issue by PeterTheOne** [Flyspray/flyspray#423]
> Markdown is a lightweight markup language with plain text formatting syntax designed so that it can be converted to HTML and many other formats using a tool by the same name.[6][7] Markdown is often used to format readme files, for writing messages in online discussion forums, and to create rich text using a plain text editor.

https://en.wikipedia.org/wiki/Markdown

**Comment by Psychokiller1888** [comment]
Please use our bug tracker @bugs.flyspray.org

**Comment by PeterTheOne** [comment]
see: https://bugs.flyspray.org/index.php?do=details&task_id=2052
