### ISSUE TITLE
demo.flyspray.org not available

### ISSUE THREAD

**Issue by ooxi** [Flyspray/flyspray#57]
I would like to test out flyspray without setting up an instance. That what your [demo installation](http://flyspray.org/demo) is for but [demo.flyspray.org](http://demo.flyspray.org/) is currently down :(

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Pelase reopen if issue still occurs

**Comment by ooxi** [comment]
As you can see for yourself [demo.flyspray.org](http://demo.flyspray.org) is still down ;)
