### ISSUE TITLE
mod_security documentation not found

### ISSUE THREAD

**Issue by ooxi** [Flyspray/flyspray#58]
The [.htaccess](https://github.com/Flyspray/flyspray/blob/master/htaccess.dist#L12) distribution file references [a blog entry](http://blog.php-security.org/archives/70-Modsecurity-vs.-PHP.html) which does not exist anymore. I suggest including the relevant information directly into the file while specifing the original author.

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Pelase reopen if issue still occurs

**Comment by ooxi** [comment]
Yes, the blog entry did not magically reappear ;)

**Comment by jordanmendler** [comment]
Patches are welcomed...

**Comment by Psychokiller1888** [comment]
Cleaned
