### ISSUE TITLE
Eval

### ISSUE THREAD

**Issue by hhirsch** [Flyspray/flyspray#60]
Do not use eval. Do not use undefined indexes. When developing enable notices.

Notice: Undefined index: tasklist_type in /x/includes/class.tpl.php(128) : eval()'d code on line 85 Notice: Undefined index: tasklist_type in /x/includes/class.tpl.php(128) : eval()'d code on line 90

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Pelase reopen if issue still occurs
