### ISSUE TITLE
Advanced Search Does not show Task Properties

### ISSUE THREAD

**Issue by bmunro-peralex** [Flyspray/flyspray#64]
Hi,

Advanced Search does not work correctly, So it is not possible to search for closed tasks.

The Task Properties do not load correctly

Working Search on 0.9.9.7 using CleanFS Theme:
![2014-11-17 13_31_32-working](https://cloud.githubusercontent.com/assets/9713415/5069119/d9a2531e-6e5e-11e4-8dbb-cb3c1db01dd4.png)

Not working search on V1.0Dev using CleanFS theme:
![2014-11-17 13_35_50_bug](https://cloud.githubusercontent.com/assets/9713415/5069120/dbbce812-6e5e-11e4-9542-42f52ade028e.png)

Versions:
flyspray: latest from github
php: 5.5.18 (Tried 5.3.29 had the same effect)
apache: 2.2.27

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Pelase reopen if issue still occurs
