### ISSUE TITLE
Pattern overflow in dokuwiki lexer and parser

### ISSUE THREAD

**Issue by Eccenux** [Flyspray/flyspray#66]
When you have a lot of comments in an issue you might get this warning:
```
Warning: preg_match(): Compilation failed: regular expression is too large at offset 63063 in /var/www/flyspray/plugins/dokuwiki/inc/parser/lexer.php on line 115
```

On PHP5 it happens for me always above 30 comments (we have some extra patterns so YMMV, but it will happen eventually). Of course showing errors would have to be enabled to see the warning.

After some debugging I noticed large increase in a regexp length in `Doku_LexerParallelRegex` (in function `_getCompoundedRegex`). When the regexp was 65628 the pattern count was 599... Also smiley pattern is repeated as many times as there are comments (plus one).

**Comment by jordanmendler** [comment]
Can you please submit a pull request so I can merge in your patch? After doing so, please close out the task

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
