### ISSUE TITLE
Upgrade 0.9.9.7 to 1.0 dev 

### ISSUE THREAD

**Issue by nicohell** [Flyspray/flyspray#68]
Hi

Today I downloaded the ZIP from github to upgrade our Flyspray and I encountered this issues : 

1/ Launching setup/upgrade.php returns : 
Parse error: syntax error, unexpected ';' in /data/www/flyspray/themes/CleanFS/templates/admin.prefs.tpl on line 150

I added the missing parenthesis, here is the new line 150 :
<label for="needapproval"><?php echo Filters::noXSS(L('regapprovedbyadmin')); ?></label>

2/ First time I tried to create a new task, I got multiples errors of missing fields (view_effort, track_effort, supertask_id, list_order, etc...) :
After a fiew search I replaced setup/upgrade/1.0/upgrade.xml by setup/upgrade/1.0/flyspray-install.xml and it solved

Hore it helps.
Nicolas

**Comment by jordanmendler** [comment]
Patches are always appreciated. Or on donations above $250 we can ear market developers to fix the issues if you reference them in the donation

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
