### ISSUE TITLE
PHP Issue with ShortTags

### ISSUE THREAD

**Issue by Mephiston** [Flyspray/flyspray#70]
Reported by @nicohell in #68 
The issues of shortcut tags are greater then the benefits, I found some shorcurt tags:

grep -r '<?=' *
themes/CleanFS/templates/newmultitasks.tpl:152:        < td colspan="<?=$field_num-2;?>"></ td>

themes/CleanFS/templates/index.tpl:381:    < tr id="task<?php echo $task_details['task_id']; ?>" class="severity<?php echo Filters::noXSS($task_details['task_severity']); ?>" onmouseover="Show(this,<?=$task_details['task_id']?>)" onmouseout="Hide(this, <?=$task_details['task_id']?>)">

themes/CleanFS/templates/index.tpl:403:< div id="desc_<?=$task_details['task_id']?>" class="descbox box">

I'm going to do a fix by my self now.

**Comment by jordanmendler** [comment]
You can do pull requests if you haven't done so already. I review those and apply if they work.

**Comment by jordanmendler** [comment]
Accepted a bunch of patches. Please reopen or submit a patch if issue still occurs.
