### ISSUE TITLE
Flyspray logo is missing in the organization

### ISSUE THREAD

**Issue by Neustradamus** [flyspray/flyspray#812]
Dear @flyspray team, @peterdd, @jordanmendler: Can you add the Flyspray logo in the organization?
- https://github.com/flyspray

**Comment by peterdd** [comment]
I added the original bottle. The quality is bad as I have currently have no better resolution available.
Based on the logo currently (2023-11-09) set on https://openhub.net/p/flyspray/

**Comment by Neustradamus** [comment]
@peterdd: It is better to have this:
- https://commons.wikimedia.org/wiki/File:Flyspray_logo.png

About OpenHub, I think that you must to request the management of the project:
- https://openhub.net/p/flyspray/

**Comment by peterdd** [comment]
Thanks for the hint. Adapted.

**Comment by Neustradamus** [comment]
Yes you must adapt the logo to have a square for GitHub logo.
Have you received my email?
If yes, please reply.

**Comment by peterdd** [comment]
done.
