### ISSUE TITLE
Flyspray Link in comment results in strange PHP network error

### ISSUE THREAD

**Issue by RickEMR** [flyspray/flyspray#857]
When adding a Flyspray link like FS#9701 to a comment I get the error message :

```
Unhandled exception: Connection could not be established with host 10.70.45.173 [Network is unreachable #101]
This should never happen, please inform Flyspray Developers.
```

This is strange, as Flyspray runs on Server with IP 172.30.6.99 maybe 10.70.45.173 is the DNS Server, but why does Flyspray try to reach it?

When returning to the task, the Flyspray link as been added correctly in the comment and is fully functional.

When using the Preview Button of the comment, then the following warning is shown (if Fylspray link is within the comment):

```
Warning: Undefined array key 3 in /var/www/html/flyspray/includes/class.flyspray.php on line 381 Warning: Undefined array key 4 in /var/www/html/flyspray/includes/class.flyspray.php on line 382 
```

**Comment by peterdd** [comment]
First maybe related to sending a notification email? Mails are always sent after handling a change, so the action(add comment) is handled before you got this error message.

Second issue I cannot reproduce yet.

**Comment by RickEMR** [comment]
Correct. The first problem is the SMTP-Server, which is stored in the prefs table of the Flyspray DB. I changed the smtp_server IP-address in the DB to 10.70.45.172 and then the error complained about 10.70.45.172 and not about 10.70.45.173 any more.
Might be worth to check the connectivity before calling the SMTP server, but this is just a "nice to have" suggestion.
Is there a way to change the SMTP server without hacking the DB?

Second problem is not very important. I will investigate it a bit more when I have some spare time.
