### ISSUE TITLE
Syntax errors in php files

### ISSUE THREAD

**Issue by zazy** [Flyspray/flyspray#87]
I cloned the master branch and found several issues to fight against:

1. in the file include/class.flyspray.php at line 683 i suppose that 
        $pwOk = ($method == 'oauth') ?: ($password == $auth_details['user_pass']);
should be something like
        $pwOk = ($method == 'oauth') ? true : ($password == $auth_details['user_pass']);

2. in file include/class.flyspray.php at line 992 there is a '\' character before the FILTER_VALIDATE_EMAIL option of the filter_var function call

3. there should be a fallback for people that can't install composer due to system access limitations (just my two cents)

**Comment by jordanmendler** [comment]
Do you mind submitted a pull request with the fixes?

**Comment by zazy** [comment]
Hi @jordanmendler , I'm new to github and still I don't know how it work so I avoided to not mess something up!... sorry! I'm a professional software developer/engineer/analyst but always used other SCC... GitHub has several confusing terms for me. ASAP I will learn how to do things in the right way so I can contribute to this great project...

**Comment by jordanmendler** [comment]
Do you know how to use git outside of github? If so I can give you commit access so you can just commit directly. Git isn't very hard and should be very simple if you've used CVS or other version control software in the past.

**Comment by zazy** [comment]
Yes, I know how to use git. It would be great so I can start contributing whenever I have spare time!

**Comment by peterdd** [comment]
I made a php syntax check test used by travis-ci in Tests/
Currently only for translation files, but can be a starting point.
