### ISSUE TITLE
Trying to register account to submit a bug to archlinux32

### ISSUE THREAD

**Issue by CthuutLoops** [flyspray/flyspray#895]
When trying to create a flyspray account to submit a bug to archlinux32 list i got an error that told me to contact the devs because it should never happen.

```
Completely unexpected exception: Call to undefined function json_decode()
This should never happend, please inform Flyspray Developers
```

**Comment by CaraesNaur** [comment]
The `json` PHP extension is not installed and enabled.

**Comment by CthuutLoops** [comment]
thanks it was fixed.
