### ISSUE TITLE
important things to be done for a 1.0 release

### ISSUE THREAD

**Issue by peterdd** [Flyspray/flyspray#91]
My personal list of requirements for a 1.0 release:

- anti-csrf token system (most important)
- rethink/rework session/cookie handling ; current cookie use is not well
- fixing some usability issues
- key features must be usable without javascript enabled for security concernd users. almost all that is handled by js currently can be replaced by html and css.
- make install and upgrade simple as a wordpress install
- basic responsive design (from 320 px wide to fullHD should be usable and look ok)
- stable estimated and effort tracking and summary of project (how many hours a project is estimated to consume and current workhours done => calculating costs) - natural with subtask data together!
- cleanup unused code, check if we really need so many jslibraries loaded.
- check if we really need so many composer dependencies

My personal wishlist:
- graphical output e.g. ganttlike diagrams realized with svg or canvas. I try to implement that.

**Comment by Psychokiller1888** [comment]
Install and upgrade are already at simplest imo, don't you think?

**Comment by peterdd** [comment]
No. What is a really simple install?
1. Download the zip and put it on your webspace.
(An extreme variant would be copy a single htmlfile to your webspace and the download and unzip is done by the installer too)
2. Point your browser to your webspace or that htmlfile and follow the localized instructions by clicking some buttons on this installer website. Done.

**Comment by Psychokiller1888** [comment]
That's what we do now, point to your website where you uploaded the files, the installer pops in, click three buttons and you're set... Except for that crap composer, but let's not argue about that

<div>-------- Message d'origine --------</div><div>De : peterdd <notifications@github.com> </div><div>Date :13/02/2015  21:23  (GMT+01:00) </div><div>A : Flyspray/flyspray <flyspray@noreply.github.com> </div><div>Cc : Psycho <laurentchervet@bluewin.ch> </div><div>Objet : Re: [flyspray] important things to be done for a 1.0 release (#91) </div><div>
</div>No. What is a really simple install?
1. Download the zip and put it on your webspace.
(An extreme variant would be copy a single htmlfile to your webspace and the download and unzip is done by the installer too)
2. Point your browser to your webspace or that htmlfile and follow the localized instructions by clicking some buttons on this installer website. Done.

**Comment by peterdd** [comment]
Well, but not every webhosting has a ssh shell available for users.

IMHO every tiny optimization at the start of install is an important thing. First impression is important for motivation. E.g. Why type /setup not simply the root folder of flyspray.

**Comment by Psychokiller1888** [comment]
About the shell, for composer, I agree totally. I didn't, so I used composer locally and uploaded everything after. A out the setup, I think you don't need to type /setup, you're redirected in it, that is if I'm not mistaken 

<div>-------- Message d'origine --------</div><div>De : peterdd <notifications@github.com> </div><div>Date :13/02/2015  21:50  (GMT+01:00) </div><div>A : Flyspray/flyspray <flyspray@noreply.github.com> </div><div>Cc : Psycho <laurentchervet@bluewin.ch> </div><div>Objet : Re: [flyspray] important things to be done for a 1.0 release (#91) </div><div>
</div>Well, but not every webhosting has a ssh shell available for users.

IMHO every tiny optimization at the start of install is an important thing. First impression is important for motivation. E.g. Why type /setup not simply the root folder of flyspray.

**Comment by Psychokiller1888** [comment]
Yep, remembered correctly, you don't have to navigate to /setup, you're redirected there from root if not yet installed...

**Comment by peterdd** [comment]
I get only

Warning: require(): Unable to access vendor/autoload.php in /var/www....  fatal.....

if the composer stuff is not installed. That should be catched by a nice greeting page with some install instructions plus a button to run the composer install.

**Comment by Psychokiller1888** [comment]
Yeah, as I said I uploaded the whole, including vendors... IMHO composer is the whole problem in flyspray. Not only most of the people don't understand it but the use isn't possible everywhere and for everyone... 

<div>-------- Message d'origine --------</div><div>De : peterdd <notifications@github.com> </div><div>Date :13/02/2015  22:36  (GMT+01:00) </div><div>A : Flyspray/flyspray <flyspray@noreply.github.com> </div><div>Cc : Psycho <laurentchervet@bluewin.ch> </div><div>Objet : Re: [flyspray] important things to be done for a 1.0 release (#91) </div><div>
</div>I get only

Warning: require(): Unable to access vendor/autoload.php in /var/www.... fatal.....

if the composer stuff is not installed. That should be catched by a nice greeting page with some install instructions plus a button to run the composer install.

**Comment by jahto** [comment]
My requirements for 1.0 are quite simple: fix anything that is really broken and causes visible errors. No new features anymore, comment out everything that is not broken but also not working, leave the rest for 1.1. Current 1.0 is almost good enough and I have it already in production.

I agree with peterdd that estimated and actual effort tracking could have some great enhancements, and with both that using composer might not have been the best solution for some users.

**Comment by Psychokiller1888** [comment]
I'm running 1.0 dev now for month, and it's stable. I commited everything I found, all these little bugs. I think we should fix the menu and a first release should be considered. It is stable, bugs will be found, and we should work with hotfixes instead of giant releases

**Comment by jahto** [comment]
I have found a few things still to fix, related to effort tracking and will do it this week, you guys please go on hunting what's still left.

**Comment by Psychokiller1888** [comment]
Been talking about releasing, we are now considering a feature freeze for the end of this month and a beta release for 1st of march. Nothing's said, but that would maybe be the plan... So, if you are to implement new things, go slowly for it, no too big changes! ;)

**Comment by Psychokiller1888** [comment]
I'll consider that most of the wanted points were made
