### ISSUE TITLE
Admin user not created after install

### ISSUE THREAD

**Issue by usefulz** [Flyspray/flyspray#95]
"That user does not exist on this Flyspray installation"

This happens after final step of install.

PHP 5.4.36-0+deb7u3 (fpm-fcgi) (built: Jan  9 2015 08:08:55)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

nginx version: nginx/1.2.1
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-log-path=/var/log/nginx/access.log --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-pcre-jit --with-debug --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_realip_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-http_xslt_module --with-ipv6 --with-sha1=/usr/include/openssl --with-md5=/usr/include/openssl --with-mail --with-mail_ssl_module --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-auth-pam --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-echo --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-upstream-fair --add-module=/tmp/buildd/nginx-1.2.1/debian/modules/nginx-dav-ext-module

Debian GNU/Linux 7 (wheezy)

Composer installed and installer ran, valid mysql credentials

**Comment by Psychokiller1888** [comment]
So that happens when the install is over, you are back at flyspray/index.php and try to login right with the username and password you provided during the installation?

**Comment by usefulz** [comment]
Correct

**Comment by jahto** [comment]
Strange, because I already fixed this once and it was committed to master on 2.2.2015. I'll check the patch once more.

**Comment by Psychokiller1888** [comment]
Fixed

Was my fault when I added "hide_my_email"

https://github.com/Flyspray/flyspray/commit/4f559d7ca3ca886ce658eb8c06b976981455a8a7

**Comment by ss89** [comment]
Once more this occurs in the current master :-(

**Comment by jahto** [comment]
Working on it. We break the installer quite often when adding new fields to database and then have wrong number of columns when adding basic data. I hope the database schema will be freezed after this time of fixing the same issue once again.

**Comment by Psychokiller1888** [comment]
Yes, we freeze in 6 days, entire project.
Still things on bugs.flyspray.org to do on the sources
