### ISSUE TITLE
hebCleanFS

### ISSUE THREAD

**Issue by Psychokiller1888** [Flyspray/flyspray#97]
This is the second theme... In my opinion, it should be dropped for 1.0 release... It wasn't maintained at all and needs complete rewrite.

I think we should focus on one theme only. After that, maybe we could consider an easy api to let people dev and propose themes for Flyspray, for free, on our webpage, bit like phpmyadmin is doing.

Any comment?

**Comment by jordanmendler** [comment]
I'm all for removing deprecated and obsolete code

_________________

Jordan Mendler
President & Chief Technology Officer
The Veloz Group | www.thevelozgroup.com
